// const autoCompleteLondon = [
//   {
//     hierarchy: "England|United Kingdom",
//     location: "51.5041174139, -0.0943465343",
//     score: 0,
//     entityName: "London",
//     entityId: "27544008",
//     entityType: "city",
//     highlight: {
//       entityName: "<em>London</em>",
//       hierarchy: "England|United Kingdom",
//     },
//     class: "City",
//     pois: [
//       {
//         entityName: "The London Eye",
//         entityId: "206569764",
//         class: "TouristAttraction",
//       },
//       {
//         entityName: "Canary Wharf",
//         entityId: "205748591",
//         class: "MetroStation",
//       },
//       {
//         entityName: "Wembley Stadium",
//         entityId: "206530852",
//         class: "TouristAttraction",
//       },
//     ],
//   },
//   {
//     hierarchy: "London|England|United Kingdom",
//     location: "51.5148388715, -0.0919688464",
//     score: 0,
//     entityName: "City of London",
//     entityId: "27562171",
//     entityType: "District",
//     highlight: {
//       entityName: "City of <em>London</em>",
//       hierarchy: "<em>London</em>|England|United Kingdom",
//     },
//     class: "District",
//     pois: null,
//   },
//   {
//     hierarchy: "London|England|United Kingdom",
//     location: "51.471389, -0.452778",
//     score: 0,
//     entityName: "London Heathrow (LHR)",
//     entityId: "95565050",
//     entityType: "airport",
//     highlight: {
//       entityName: "<em>London</em> Heathrow (LHR)",
//       hierarchy: "<em>London</em>|England|United Kingdom",
//     },
//     class: "Airport",
//     pois: null,
//   },
//   {
//     hierarchy: "London|England|United Kingdom",
//     location: "51.5215, -0.04934",
//     score: 0,
//     entityName: "London Central",
//     entityId: "216931578",
//     entityType: "hotel",
//     highlight: {
//       entityName: "<em>London</em> Central",
//       hierarchy: "<em>London</em>|England|United Kingdom",
//     },
//     class: "Hotel",
//     pois: null,
//   },
//   {
//     hierarchy: "London|England|United Kingdom",
//     location: "51.148056, -0.196667",
//     score: 0,
//     entityName: "London Gatwick (LGW)",
//     entityId: "95565051",
//     entityType: "airport",
//     highlight: {
//       entityName: "<em>London</em> Gatwick (LGW)",
//       hierarchy: "<em>London</em>|England|United Kingdom",
//     },
//     class: "Airport",
//     pois: null,
//   },
//   {
//     hierarchy: "London|England|United Kingdom",
//     location: "51.5135442819, -0.1353110741",
//     score: 0,
//     entityName: "Soho",
//     entityId: "115260367",
//     entityType: "District",
//     highlight: {
//       entityName: "Soho",
//       hierarchy: "<em>London</em>|England|United Kingdom",
//     },
//     class: "District",
//     pois: null,
//   },
//   {
//     hierarchy: "London|England|United Kingdom",
//     location: "51.5311162, -0.1258659",
//     score: 0,
//     entityName: "St Pancras International Station",
//     entityId: "207975505",
//     entityType: "Train Station",
//     highlight: {
//       entityName: "St Pancras International Station",
//       hierarchy: "<em>London</em>|England|United Kingdom",
//     },
//     class: "TrainStation",
//     pois: null,
//   },
//   {
//     hierarchy: "London|England|United Kingdom",
//     location: "51.515806, -0.180209",
//     score: 0,
//     entityName: "Park Grand London Hyde Park",
//     entityId: "95812669",
//     entityType: "hotel",
//     highlight: {
//       entityName: "Park Grand <em>London</em> Hyde Park",
//       hierarchy: "<em>London</em>|England|United Kingdom",
//     },
//     class: "Hotel",
//     pois: null,
//   },
//   {
//     hierarchy: "London|Ontario|Canada",
//     location: "43.04, -81.15",
//     score: 0,
//     entityName: "London (YXU)",
//     entityId: "95673743",
//     entityType: "airport",
//     highlight: {
//       entityName: "<em>London</em> (YXU)",
//       hierarchy: "<em>London</em>|Ontario|Canada",
//     },
//     class: "Airport",
//     pois: null,
//   },
// ];

const autoCompleteNewYork = [
  {
    hierarchy: "New York|United States",
    location: "40.6940959901, -73.9282670243",
    score: 0,
    entityName: "New York",
    entityId: "27537542",
    entityType: "city",
    highlight: {
      entityName: "<em>New</em> York",
      hierarchy: "<em>New</em> York|United States",
    },
    class: "City",
    pois: null,
  },
  {
    hierarchy: "Louisiana|United States",
    location: "30.068836083752895, -89.92997610444357",
    score: 0,
    entityName: "New Orleans",
    entityId: "35234892",
    entityType: "city",
    highlight: {
      entityName: "<em>New</em> Orleans",
      hierarchy: "Louisiana|United States",
    },
    class: "City",
    pois: null,
  },
  {
    hierarchy: "New York|New York|United States",
    location: "40.7738002597, -73.9697378906",
    score: 0,
    entityName: "Manhattan",
    entityId: "27562849",
    entityType: "District",
    highlight: {
      entityName: "Manhattan",
      hierarchy: "<em>New</em> York|New York|United States",
    },
    class: "District",
    pois: null,
  },
  {
    hierarchy: "United States",
    location: "40.1660048818, -74.6656028817",
    score: 0,
    entityName: "New Jersey",
    entityId: "44294284",
    entityType: "region",
    highlight: {
      entityName: "<em>New</em> Jersey",
      hierarchy: "United States",
    },
    class: "FirstLevelNationAdministrativeDivision",
    pois: null,
  },
  {
    hierarchy: "New Jersey|United States",
    location: "40.7356568999, -74.1723670522",
    score: 0,
    entityName: "Newark",
    entityId: "27540983",
    entityType: "city",
    highlight: {
      entityName: "<em>New</em>ark",
      hierarchy: "<em>New</em> Jersey|United States",
    },
    class: "City",
    pois: null,
  },
  {
    hierarchy: "New York|New York|United States",
    location: "40.75802199374021, -73.98554737024692",
    score: 0,
    entityName: "Times Square",
    entityId: "95569657",
    entityType: "Square",
    highlight: {
      entityName: "Times Square",
      hierarchy: "<em>New</em> York|New York|United States",
    },
    class: "TransitwayPlaza",
    pois: null,
  },
  {
    hierarchy: "Newport County|Rhode Island|United States",
    location: "41.4901023859, -71.3128283734",
    score: 0,
    entityName: "Newport",
    entityId: "27545144",
    entityType: "city",
    highlight: {
      entityName: "<em>New</em>port",
      hierarchy: "<em>New</em>port County|Rhode Island|United States",
    },
    class: "City",
    pois: null,
  },
  {
    hierarchy: "New Orleans|Louisiana|United States",
    location: "30.039444, -90.026667",
    score: 0,
    entityName: "New Orleans Lakefront (NEW)",
    entityId: "129054315",
    entityType: "airport",
    highlight: {
      entityName: "<em>New</em> Orleans Lakefront (<em>NEW</em>)",
      hierarchy: "<em>New</em> Orleans|Louisiana|United States",
    },
    class: "Airport",
    pois: null,
  },
  {
    hierarchy: "Delhi|India",
    location: "28.576468627850492, 77.14825704981389",
    score: 0,
    entityName: "New Delhi",
    entityId: "27540706",
    entityType: "city",
    highlight: { entityName: "<em>New</em> Delhi", hierarchy: "Delhi|India" },
    class: "City",
    pois: null,
  },
  {
    hierarchy: "New York|New York|United States",
    location: "40.695833, -74.171667",
    score: 0,
    entityName: "New York Newark (EWR)",
    entityId: "95565059",
    entityType: "airport",
    highlight: {
      entityName: "<em>New</em> York Newark (EWR)",
      hierarchy: "<em>New</em> York|New York|United States",
    },
    class: "Airport",
    pois: null,
  },
];

// const autoCompleteJapan = [
//   {
//     hierarchy: "",
//     location: "37.31327272144959, 137.6721328885855",
//     score: 0,
//     entityName: "Japan",
//     entityId: "29475330",
//     entityType: "Country",
//     highlight: { entityName: "<em>Japan</em>", hierarchy: "" },
//     class: "Nation",
//     pois: null,
//   },
//   {
//     hierarchy: "Tokyo|Japan",
//     location: "29.992220724554866, 140.76724260851924",
//     score: 0,
//     entityName: "Tokyo",
//     entityId: "27542089",
//     entityType: "city",
//     highlight: { entityName: "", hierarchy: "Tokyo|<em>Japan</em>" },
//     class: "City",
//     pois: null,
//   },
//   {
//     hierarchy: "Osaka Prefecture|Japan",
//     location: "34.66232837098631, 135.46977019822467",
//     score: 0,
//     entityName: "Osaka",
//     entityId: "27542908",
//     entityType: "city",
//     highlight: {
//       entityName: "Osaka",
//       hierarchy: "Osaka Prefecture|<em>Japan</em>",
//     },
//     class: "City",
//     pois: null,
//   },
//   {
//     hierarchy: "Fukuoka-shi|Fukuoka Prefecture|Japan",
//     location: "33.808777813220296, 130.4609497293429",
//     score: 0,
//     entityName: "Fukuoka",
//     entityId: "27541740",
//     entityType: "city",
//     highlight: {
//       entityName: "Fukuoka",
//       hierarchy: "Fukuoka-shi|Fukuoka Prefecture|<em>Japan</em>",
//     },
//     class: "City",
//     pois: null,
//   },
//   {
//     hierarchy: "Kyōto-shi|Kyoto Prefecture|Japan",
//     location: "35.106104588661374, 135.72736698108184",
//     score: 0,
//     entityName: "Kyoto",
//     entityId: "27548351",
//     entityType: "city",
//     highlight: {
//       entityName: "",
//       hierarchy: "Kyōto-shi|Kyoto Prefecture|<em>Japan</em>",
//     },
//     class: "City",
//     pois: null,
//   },
//   {
//     hierarchy: "Sapporo-shi|Hokkaido|Japan",
//     location: "42.99473709254721, 141.2495896254364",
//     score: 0,
//     entityName: "Sapporo",
//     entityId: "27537553",
//     entityType: "city",
//     highlight: {
//       entityName: "Sapporo",
//       hierarchy: "Sapporo-shi|Hokkaido|<em>Japan</em>",
//     },
//     class: "City",
//     pois: null,
//   },
//   {
//     hierarchy: "Okinawa-shi|Okinawa Prefecture|Japan",
//     location: "26.34122771064883, 127.81755118022764",
//     score: 0,
//     entityName: "Okinawa",
//     entityId: "27540768",
//     entityType: "city",
//     highlight: {
//       entityName: "Okinawa",
//       hierarchy: "Okinawa-shi|Okinawa Prefecture|<em>Japan</em>",
//     },
//     class: "City",
//     pois: null,
//   },
//   {
//     hierarchy: "Aichi Prefecture|Japan",
//     location: "35.14072470022754, 136.92139532516137",
//     score: 0,
//     entityName: "Nagoya",
//     entityId: "27545106",
//     entityType: "city",
//     highlight: {
//       entityName: "Nagoya",
//       hierarchy: "Aichi Prefecture|<em>Japan</em>",
//     },
//     class: "City",
//     pois: null,
//   },
//   {
//     hierarchy: "Hiroshima-shi|Hiroshima Prefecture|Japan",
//     location: "34.4663056372474, 132.45108937222668",
//     score: 0,
//     entityName: "Hiroshima",
//     entityId: "27542057",
//     entityType: "city",
//     highlight: {
//       entityName: "Hiroshima",
//       hierarchy: "Hiroshima-shi|Hiroshima Prefecture|<em>Japan</em>",
//     },
//     class: "City",
//     pois: null,
//   },
//   {
//     hierarchy: "Yokohama-shi|Kanagawa Prefecture|Japan",
//     location: "35.46025521362837, 139.57755297075357",
//     score: 0,
//     entityName: "Yokohama",
//     entityId: "27551106",
//     entityType: "city",
//     highlight: {
//       entityName: "Yokohama",
//       hierarchy: "Yokohama-shi|Kanagawa Prefecture|<em>Japan</em>",
//     },
//     class: "City",
//     pois: null,
//   },
// ];
