export const reviewsNewYork = {
  reviews: [
    {
      hotelId: 46944653,
      userIcon: "business",
      userIconColor: "Valensole",
      userType: "Business traveller",
      checkinDate: "2024-06",
      checkinDateDesc: "Date of stay:",
      partnerLogo:
        "https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s1.0-64600-5.svg",
      tripType: "Business trip",
      isShowMachineTranslation: false,
      isNeedMachineTranslation: false,
      locale: "en-GB",
      rating: 1,
      formatRating: "1.0",
      review: {
        text: "I had to wait for the elevator for 30 minutes, making me late for my meetings. This is unacceptable and I would not recommend any business traveler with a tight schedule to stay in this property.",
        title: "Only 1 elevator working for 55 floors",
        images: [],
        commentDate: "2024-06-15",
        commentDateDesc: "Comment:",
      },
      reviewId: 555709769,
      countryName: null,
      totalRating: 5,
      partner: "h_vs",
      link: "https://en.tripadvisor.com.hk/Hotel_Review-d262330-a_ho.1-Reviews?m=64600",
      partnerReviewId: "955261858",
      userLocation: null,
      countryImage: null,
      likeNum: 0,
      scoreDesc: "Average",
    },
    {
      hotelId: 46944653,
      userIcon: "business",
      userIconColor: "Valensole",
      userType: "Business traveller",
      checkinDate: "2024-06",
      checkinDateDesc: "Date of stay:",
      partnerLogo:
        "https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s1.0-64600-5.svg",
      tripType: "Business trip",
      isShowMachineTranslation: false,
      isNeedMachineTranslation: false,
      locale: "en-GB",
      rating: 1,
      formatRating: "1.0",
      review: {
        text: "The moment we walked in and was at the front desk to check In, It was bad, it only gotten worse and we wouldn't know what lied ahead when we walked into our room! In which was the nasty hotel I have seen. Not only this room but 4 room later. Still was not okay. Bathroom smelled like sewage water all day, elevator was broken.\n\nCarpet nasty, the beds were old and warm out like the old school Pink & blue ones! The most uncomfortable stay l have ever experienced at a hotel. Please If you can book anywhere but here please do! As we were checking in another couple was complaining, didn't think much until we arrived to our room and understood why! I even asked for a single room instead of a suite If It was better condition. The manager walked out and said NO that was not possible as the single rooms were priced higher than a suite. She had an attitude and was of no help!! Another girl approached and walked with us to a few of the rooms to see herself, & apologized for the conditions of the rooms! I knew It was not her fault, but planning this for months to show up and see the conditions was horrible for me & my family. On top of that I received a price from Booking and the hotel charged me way more than the price I was given on confirmation. I can go on & on. Just use another hotel save yourself from the headaches.",
        title: "Nasty Rooms",
        images: [],
        commentDate: "2024-06-15",
        commentDateDesc: "Comment:",
      },
      reply: {
        text: "cknowl705488,\n\nWe regret to hear that the experience did not meet your expectations. Cleanliness and comfort are top priorities, and it’s unfortunate that the visit did not reflect this. It’s disappointing that the accommodations and service did not meet your needs, and we appreciate your feedback. Your comments will be used to improve future stays for our guests.",
        commentDate: "2024-06-15",
        title: "Hotel response",
      },
      reviewId: 555709770,
      countryName: null,
      totalRating: 5,
      partner: "h_vs",
      link: "https://en.tripadvisor.com.hk/Hotel_Review-d262330-a_ho.1-Reviews?m=64600",
      partnerReviewId: "955201239",
      userLocation: null,
      countryImage: null,
      likeNum: 0,
      scoreDesc: "Average",
    },
    {
      hotelId: 46944653,
      userIcon: "business",
      userIconColor: "Valensole",
      userType: "Business traveller",
      checkinDate: "2024-06",
      checkinDateDesc: "Date of stay:",
      partnerLogo:
        "https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s1.0-64600-5.svg",
      tripType: "Business trip",
      isShowMachineTranslation: false,
      isNeedMachineTranslation: false,
      locale: "en-GB",
      rating: 1,
      formatRating: "1.0",
      review: {
        text: "This really affected the stay. You can’t have such a big building with only one elevator. And the staff really didn’t care!!!",
        title:
          "Only one elevator for 4 days in a 55 stories hotel. Shocking!!!",
        images: [],
        commentDate: "2024-06-15",
        commentDateDesc: "Comment:",
      },
      reviewId: 555709771,
      countryName: null,
      totalRating: 5,
      partner: "h_vs",
      link: "https://en.tripadvisor.com.hk/Hotel_Review-d262330-a_ho.1-Reviews?m=64600",
      partnerReviewId: "955184218",
      userLocation: null,
      countryImage: null,
      likeNum: 0,
      scoreDesc: "Average",
    },
    {
      hotelId: 46944653,
      userIcon: "account",
      userIconColor: "SkyGrayTint04",
      userType: "Anonymous traveller",
      checkinDate: "2024-06",
      checkinDateDesc: "Date of stay:",
      partnerLogo:
        "https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s3.0-64600-5.svg",
      tripType: "",
      isShowMachineTranslation: false,
      isNeedMachineTranslation: false,
      locale: "en-GB",
      rating: 3,
      formatRating: "3.0",
      review: {
        text: "Great view of lower Manhattan. Within walking distance of restaurants, subways, downtown shops, parks, the memorial of 9/11, and the Brooklyn Bridge. Comfortable king size bed, spacious bathroom, plenty of lighting, and wall to wall windows for a great view of the city. My only complaints would bee the chairs in the room were stained and dirty, the light hanging from the ceiling would buzz loudly when turned on, and hallway carpets were dirty.  I gave an average rating because the only thing spectacular about the room was the view. Other than that it's just your average hotel room.",
        title: "Great view and location",
        images: [],
        commentDate: "2024-06-14",
        commentDateDesc: "Comment:",
      },
      reply: {
        text: "Litney, thank you for sharing your feedback. It's great to hear you enjoyed the view of lower Manhattan and appreciated the convenient location and room amenities. We're sorry you encountered issues with room cleanliness and lighting. Your feedback will be shared with our team members to help enhance our services. We hope to have another chance to provide you with an improved experience in the future.",
        commentDate: "2024-06-15",
        title: "Hotel response",
      },
      reviewId: 555709772,
      countryName: null,
      totalRating: 5,
      partner: "h_vs",
      link: "https://en.tripadvisor.com.hk/Hotel_Review-d262330-a_ho.1-Reviews?m=64600",
      partnerReviewId: "955145036",
      userLocation: null,
      countryImage: null,
      likeNum: 0,
      scoreDesc: "Satisfactory",
    },
    {
      hotelId: 46944653,
      userIcon: "business",
      userIconColor: "Valensole",
      userType: "Business traveller",
      checkinDate: "2024-06",
      checkinDateDesc: "Date of stay:",
      partnerLogo:
        "https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s3.0-64600-5.svg",
      tripType: "Business trip",
      isShowMachineTranslation: false,
      isNeedMachineTranslation: false,
      locale: "en-GB",
      rating: 3,
      formatRating: "3.0",
      review: {
        text: "elevators, clocks, lights, not all of these items worked! air only got to 78 in my suite, just not suitable for a good conference.  two rooms two clocks not working and not to even mention the elevators!",
        title: "not everything works at this hotel!",
        images: [],
        commentDate: "2024-06-14",
        commentDateDesc: "Comment:",
      },
      reply: {
        text: "susanmyers2024, thank you for sharing your feedback. We regret to hear about the inconveniences you encountered during your stay. Your comments are vital and will help us improve our services and amenities. We hope you will consider giving us another opportunity in the future to provide you with a more pleasant experience.",
        commentDate: "2024-06-15",
        title: "Hotel response",
      },
      reviewId: 555709773,
      countryName: null,
      totalRating: 5,
      partner: "h_vs",
      link: "https://en.tripadvisor.com.hk/Hotel_Review-d262330-a_ho.1-Reviews?m=64600",
      partnerReviewId: "955090551",
      userLocation: null,
      countryImage: null,
      likeNum: 0,
      scoreDesc: "Satisfactory",
    },
    {
      hotelId: 46944653,
      userIcon: "toilets",
      userIconColor: "Hillier",
      userType: "Couple",
      checkinDate: "",
      checkinDateDesc: "Date of stay:",
      partnerLogo: "https://www.skyscanner.com/images/websites/220x80/d_ct.png",
      tripType: "Couple's trip",
      isShowMachineTranslation: false,
      isNeedMachineTranslation: false,
      locale: "en-GB",
      rating: 3.2,
      formatRating: "3.2",
      review: {
        text: "1. Poor WiFi\n2. Unstable hot water for shower\n3. Excellent view and location \n4. Excellent doorman",
        title: null,
        images: [],
        commentDate: "2023-09-04",
        commentDateDesc: "Comment:",
      },
      reviewId: 481064230,
      countryName: null,
      totalRating: 5,
      partner: "d_ct",
      link: null,
      partnerReviewId: "918933028",
      userLocation: null,
      countryImage: null,
      likeNum: 0,
      scoreDesc: "Good",
    },
    {
      hotelId: 46944653,
      userIcon: "business",
      userIconColor: "Valensole",
      userType: "Business traveller",
      checkinDate: "",
      checkinDateDesc: "Date of stay:",
      partnerLogo: "https://www.skyscanner.com/images/websites/220x80/d_ct.png",
      tripType: "Business trip",
      isShowMachineTranslation: false,
      isNeedMachineTranslation: false,
      locale: "en-GB",
      rating: 2,
      formatRating: "2.0",
      review: {
        text: "Worst experience, unfriendly, huge hidden charges out of contract, old, dirty, phone didn’t work,lifts didn’t work, bar was closed most of the times. It had nice views for all they are worthy when nothing else is in place. Stay away",
        title: null,
        images: [],
        commentDate: "2023-02-16",
        commentDateDesc: "Comment:",
      },
      reviewId: 438815791,
      countryName: null,
      totalRating: 5,
      partner: "d_ct",
      link: null,
      partnerReviewId: "730096353",
      userLocation: null,
      countryImage: null,
      likeNum: 0,
      scoreDesc: "Satisfactory",
    },
    {
      hotelId: 46944653,
      userIcon: "business",
      userIconColor: "Valensole",
      userType: "Business traveller",
      checkinDate: "",
      checkinDateDesc: "Date of stay:",
      partnerLogo: "https://www.skyscanner.com/images/websites/220x80/d_ct.png",
      tripType: "Business trip",
      isShowMachineTranslation: false,
      isNeedMachineTranslation: false,
      locale: "en-GB",
      rating: 1,
      formatRating: "1.0",
      review: {
        text: "This is a very bad trip！ the worse !! . First of all, the hotel facilities are very old. Secondly, such a big hotel lost consumer things. After losing consumer things, they didn't cooperate to find them. It was all kinds of delays!  I was dragged until I had to leave because they knew that I had to catch a plane for the next trip. At the same time, hotel promised to call or email me to inform me of the progress. But they didn't. A 5-minute camera secret checking was watched for two hours.  And didn’t check yet whether I was there or not. Such a big group training was done so badly. And the service attitude of “I’m just a person who working here ” i mean … whaaaa ? In this way to deal with customers. I’m really disappointed with this company!",
        title: null,
        images: [],
        commentDate: "2023-01-12",
        commentDateDesc: "Comment:",
      },
      reviewId: 438815789,
      countryName: null,
      totalRating: 5,
      partner: "d_ct",
      link: null,
      partnerReviewId: "708030399",
      userLocation: null,
      countryImage: null,
      likeNum: 0,
      scoreDesc: "Average",
    },
    {
      hotelId: 46944653,
      userIcon: "adult",
      userIconColor: "Glencoe",
      userType: "Solo traveller",
      checkinDate: "",
      checkinDateDesc: "Date of stay:",
      partnerLogo: "https://www.skyscanner.com/images/websites/220x80/d_ct.png",
      tripType: "Solo trip",
      isShowMachineTranslation: true,
      isNeedMachineTranslation: false,
      locale: "en-GB",
      rating: 4.7,
      formatRating: "4.7",
      review: {
        text: "The landscape is not bad",
        title: null,
        images: [],
        commentDate: "2023-01-12",
        commentDateDesc: "Comment:",
      },
      reviewId: 417701894,
      countryName: null,
      totalRating: 5,
      partner: "d_ct",
      link: null,
      partnerReviewId: "707933821",
      userLocation: null,
      countryImage: null,
      likeNum: 0,
      scoreDesc: "Outstanding",
    },
    {
      hotelId: 46944653,
      userIcon: "toilets",
      userIconColor: "Hillier",
      userType: "Couple",
      checkinDate: "",
      checkinDateDesc: "Date of stay:",
      partnerLogo: "https://www.skyscanner.com/images/websites/220x80/d_ct.png",
      tripType: "Couple's trip",
      isShowMachineTranslation: true,
      isNeedMachineTranslation: false,
      locale: "en-GB",
      rating: 3.2,
      formatRating: "3.2",
      review: {
        text: "No water is given, paper towels are used up and the inventory is out of stock, disposable slippers are not provided, refrigerators and microwave ovens are charged, and the service is mediocre. The location is good, just outside the subway and business district.",
        title: null,
        images: [],
        commentDate: "2023-01-11",
        commentDateDesc: "Comment:",
      },
      reviewId: 417701914,
      countryName: null,
      totalRating: 5,
      partner: "d_ct",
      link: null,
      partnerReviewId: "707570727",
      userLocation: null,
      countryImage: null,
      likeNum: 0,
      scoreDesc: "Good",
    },
  ],
  searchStatus: {
    completed: false,
    reviewPartner: [
      {
        partnerId: "h_vs",
        total: 6867,
        score: 4,
        taScoreImage:
          "https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.0-64600-4.png",
      },
      { partnerId: "d_ct", total: 84, score: 4.1, ctripTotalAvailable: 84 },
    ],
  },
  title: "What other travelers are saying",
  cta: "See more",
  summaryCTA: "Where are these ratings from?",
  dialogTitle: "So, what do other travelers think?",
  dialogDescription:
    "Find out what this hotel is really like from people who’ve actually stayed there.\n{strong}Ratings{/strong} are out of 10 on things like the location, amenities and customer service.\n{strong}Reviews{/strong} give you more first-hand detail about their experience.",
  dialogCTA: "Got it",
  pageTitle: "Reviews",
  pageCTA: "See prices",
  filters: [
    {
      type: "guest_type",
      title: "Traveler type",
      values: [
        {
          id: "all",
          count: 84,
          label: "All travelers(84)",
          title: "All travelers",
        },
        {
          id: "business",
          count: 33,
          label: "Business traveller (33)",
          title: "Business traveller",
        },
        { id: "couple", count: 11, label: "Couple (11)", title: "Couple" },
        {
          id: "family",
          count: 15,
          label: "Family traveller (15)",
          title: "Family traveller",
        },
        {
          id: "group",
          count: 10,
          label: "Group traveller (10)",
          title: "Group traveller",
        },
        {
          id: "other",
          count: 6,
          label: "Anonymous traveller (6)",
          title: "Anonymous traveller",
        },
        {
          id: "solo",
          count: 9,
          label: "Solo traveller (9)",
          title: "Solo traveller",
        },
      ],
    },
    {
      type: "filter_locale",
      title: "Language",
      values: [
        {
          id: "all",
          count: 84,
          label: "All languages(84)",
          title: "All languages",
        },
        { id: "de-DE", count: 1, label: "Deutsch (1)", title: "Deutsch" },
        {
          id: "en-GB",
          count: 21,
          label: "English (United Kingdom) (21)",
          title: "English (United Kingdom)",
        },
        { id: "fr-FR", count: 1, label: "français (1)", title: "français" },
        { id: "ko-KR", count: 3, label: "한국어 (3)", title: "한국어" },
        { id: "zh-CN", count: 56, label: "简体中文 (56)", title: "简体中文" },
        { id: "zh-TW", count: 2, label: "繁體中文 (2)", title: "繁體中文" },
      ],
    },
    {
      type: "sort",
      title: "Sort by",
      values: [
        {
          id: "recommended",
          count: 0,
          label: "Recommended",
          title: "Recommended",
        },
        {
          id: "rating_desc",
          count: 0,
          label: "Rating (high to low)",
          title: "Rating (high to low)",
        },
        {
          id: "rating_asc",
          count: 0,
          label: "Rating (low to high)",
          title: "Rating (low to high)",
        },
        {
          id: "LAST_TWELVE_MONTHS",
          count: 0,
          label: "Most recent",
          title: "Most recent",
        },
      ],
    },
    {
      type: "tags",
      title: "tags",
      values: [
        {
          id: "1",
          count: 14,
          label: "Reviews with photos (14)",
          title: "WITH_IMAGES",
        },
        {
          id: "location",
          count: 36,
          label: "Location (36)",
          title: "Location",
        },
        { id: "service", count: 15, label: "Service (15)", title: "Service" },
        { id: "room", count: 12, label: "Room (12)", title: "Room" },
        {
          id: "transportation",
          count: 11,
          label: "Transportation (11)",
          title: "Transportation",
        },
        { id: "scenery", count: 7, label: "Views (7)", title: "Views" },
        { id: "quiet", count: 3, label: "Quiet (3)", title: "Quiet" },
        { id: "clean", count: 2, label: "Clean (2)", title: "Clean" },
        {
          id: "shop",
          count: 2,
          label: "Shopping area (2)",
          title: "Shopping area",
        },
        { id: "bathroom", count: 1, label: "Bathroom (1)", title: "Bathroom" },
        { id: "family", count: 1, label: "Family (1)", title: "Family" },
        { id: "meal", count: 1, label: "Meal (1)", title: "Meal" },
        { id: "wifi", count: 1, label: "WiFi (1)", title: "WiFi" },
      ],
    },
  ],
};
